#!/bin/bash
set -euo pipefail

if [[ $EUID -ne 0 ]]; then
    echo "This script must be run as root."
    exit 1
fi

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
CONFIG="$SCRIPT_DIR/config.local"

DEFAULT_CTID=100
DEFAULT_IP="10.10.10.10"
DEFAULT_PORT=8000
DEFAULT_HOSTNAME="paperless"
DEFAULT_CONSUME_HOST_PATH="/mnt/paperless/consume"
DEFAULT_STORAGE_HOST_PATH="/mnt/paperless/storage"

if [[ -f "$CONFIG" ]]; then
    # shellcheck source=/dev/null
    source "$CONFIG"

    DEFAULT_CTID="${PAPERLESS_CTID:-$DEFAULT_CTID}"
    DEFAULT_IP="${PAPERLESS_IP:-$DEFAULT_IP}"
    DEFAULT_PORT="${PAPERLESS_PORT:-$DEFAULT_PORT}"
    DEFAULT_HOSTNAME="${PAPERLESS_HOSTNAME:-$DEFAULT_HOSTNAME}"
    DEFAULT_CONSUME_HOST_PATH="${PAPERLESS_CONSUME_HOST_PATH:-$DEFAULT_CONSUME_HOST_PATH}"
    DEFAULT_STORAGE_HOST_PATH="${PAPERLESS_STORAGE_HOST_PATH:-$DEFAULT_STORAGE_HOST_PATH}"
fi

read -r -p "Container ID [$DEFAULT_CTID]: " PAPERLESS_CTID
PAPERLESS_CTID="${PAPERLESS_CTID:-$DEFAULT_CTID}"

read -r -p "Container IP [$DEFAULT_IP]: " PAPERLESS_IP
PAPERLESS_IP="${PAPERLESS_IP:-$DEFAULT_IP}"

read -r -p "Paperless port [$DEFAULT_PORT]: " PAPERLESS_PORT
PAPERLESS_PORT="${PAPERLESS_PORT:-$DEFAULT_PORT}"

read -r -p "Container hostname [$DEFAULT_HOSTNAME]: " PAPERLESS_HOSTNAME
PAPERLESS_HOSTNAME="${PAPERLESS_HOSTNAME:-$DEFAULT_HOSTNAME}"

read -r -p \
    "Local consume path [$DEFAULT_CONSUME_HOST_PATH]: " \
    PAPERLESS_CONSUME_HOST_PATH

PAPERLESS_CONSUME_HOST_PATH="${PAPERLESS_CONSUME_HOST_PATH:-$DEFAULT_CONSUME_HOST_PATH}"

read -r -p \
    "Local storage path [$DEFAULT_STORAGE_HOST_PATH]: " \
    PAPERLESS_STORAGE_HOST_PATH

PAPERLESS_STORAGE_HOST_PATH="${PAPERLESS_STORAGE_HOST_PATH:-$DEFAULT_STORAGE_HOST_PATH}"

cat > "$CONFIG" <<EOF
PAPERLESS_CTID="$PAPERLESS_CTID"
PAPERLESS_IP="$PAPERLESS_IP"
PAPERLESS_PORT="$PAPERLESS_PORT"
PAPERLESS_HOSTNAME="$PAPERLESS_HOSTNAME"

PAPERLESS_CONSUME_HOST_PATH="$PAPERLESS_CONSUME_HOST_PATH"
PAPERLESS_STORAGE_HOST_PATH="$PAPERLESS_STORAGE_HOST_PATH"
EOF

chmod 600 "$CONFIG"

echo
echo "Configuration written to:"
echo "  $CONFIG"
echo
echo "Host paths:"
echo "  Consume: $PAPERLESS_CONSUME_HOST_PATH"
echo "  Storage: $PAPERLESS_STORAGE_HOST_PATH"
